=== thearchitectx/LIS/Assets/StreamingAssets/Cutscene.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="dialogStyle">
        <xs:restriction base="xs:string">
            <xs:enumeration value="whisper"/>
            <xs:enumeration value="remote"/>
            <xs:enumeration value="remote-subjective"/>
            <xs:enumeration value="default"/>
            <xs:enumeration value="subjective"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="fadeToBlackMode">
        <xs:restriction base="xs:string">
            <xs:enumeration value="to"/>
            <xs:enumeration value="from" />
            <xs:enumeration value="to-from" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="prefab">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PictureViewer"/>
            <xs:enumeration value="PictureTaker" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cutscene-outcome">
        <xs:restriction base="xs:string">
            <xs:enumeration value="_destroyObject"/>
            <xs:enumeration value="_destroyParent"/>
            <xs:enumeration value="_end"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="bone">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Hips" />
            <xs:enumeration value="Spine" />
            <xs:enumeration value="Spine1" />
            <xs:enumeration value="Spine2" />
            <xs:enumeration value="Neck" />
            <xs:enumeration value="Head" />
            <xs:enumeration value="LeftEye" />
            <xs:enumeration value="RightEye" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="text-data">
        <xs:restriction base="xs:string">
            <xs:enumeration value="KATE_HALLWAY_PICTURE" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="perk">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PRK_SMELLY" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="choiceIcon">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DICK_INTELLIGENCE" />
            <xs:enumeration value="DICK_CHARISMA" />
            <xs:enumeration value="DICK_KARMA_GOOD" />
            <xs:enumeration value="DICK_KARMA_EVIL" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="flag">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DICK_DARING" />
            <xs:enumeration value="DICK_INTELLIGENCE" />
            <xs:enumeration value="DICK_CHARISMA" />
            <xs:enumeration value="DICK_KARMA" />
            <xs:enumeration value="CLASSROOM_TRASH_CAN_TRASH_COUNT" />
            <xs:enumeration value="BROOKE_MET" />
            <xs:enumeration value="BROOKE_ABOUT_MAX_AND WARREN" /> <!-- (1)Propose revenge (2)Tried to help -->
            <xs:enumeration value="HALLWAY_TRASH_CAN_A_TRASH_COUNT" />
            <xs:enumeration value="HALLWAY_TRASH_CAN_B_TRASH_COUNT" />
            <xs:enumeration value="HALLWAY_TRASH_CAN_C_TRASH_COUNT" />
            <xs:enumeration value="HALLWAY_TRASH_CAN_D_TRASH_COUNT" />
            <xs:enumeration value="HALLWAY_TRIED_ENTER_ROOM103" />
            <xs:enumeration value="INTRO_TRASH_SCORE" />
            <xs:enumeration value="INTRO_TALK_VICTORIA" />
            <xs:enumeration value="INTRO_CHECK_VICTORIA" />
            <xs:enumeration value="JULIE_ZACHARY_MAKE_OUT_SEEN" />
            <xs:enumeration value="KATE_FIRST_MET" />
            <xs:enumeration value="PICKED_BROOKE_NOTE" />
            <xs:enumeration value="QUEST_BROOKE_CARD" /> <!-- (1)Started  -->
            <xs:enumeration value="QUEST_KATE_LOCKER" /> <!-- (1)Started (2)Searching Key (3)Delivered Key</xs:documentation></xs:annotation></xs:enumeration -->
            <xs:enumeration value="QUEST_JEFFERSON_TAKE_PIC" /><!-- (1)Took Lame Pic (2)Took cool pic (11)Delivered Lame pic (12)Delivered Cool Pic -->
            <xs:enumeration value="TMP_1" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="character-stat">
        <xs:restriction base="xs:string">
            <xs:enumeration value="AFFINITY" />
            <xs:enumeration value="INTEL" />
            <xs:enumeration value="INTEL_0" />
            <xs:enumeration value="INTEL_1" />
            <xs:enumeration value="INTEL_2" />
            <xs:enumeration value="INTEL_3" />
            <xs:enumeration value="INTEL_4" />
            <xs:enumeration value="INTEL_5" />
            <xs:enumeration value="INTEL_6" />
            <xs:enumeration value="INTEL_7" />
            <xs:enumeration value="INTEL_8" />
            <xs:enumeration value="INTEL_9" />
            <xs:enumeration value="CORRUPTION" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="objective">
        <xs:restriction base="xs:string">
            <xs:enumeration value="OBJ_BrookeMemoryCard" />
            <xs:enumeration value="OBJ_IntroCollectTrash" />
            <xs:enumeration value="OBJ_IntroTalk" />
            <xs:enumeration value="OBJ_JeffersonFirstPicTake" />
            <xs:enumeration value="OBJ_KateHelpLockerOpenLocker" />
            <xs:enumeration value="OBJ_KateHelpLockerFindKey" />
            <xs:enumeration value="OBJ_JeffersonFirstPicBring" />
            <xs:enumeration value="OBJ_TalkToThePrincipal" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="item">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ITM_LOCKER_KEY" />
            <xs:enumeration value="ITM_MONEY" />
            <xs:enumeration value="ITM_TRASH" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="character">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CH_Brooke" />
            <xs:enumeration value="CH_Kate" />
            <xs:enumeration value="CH_Jefferson" />
            <xs:enumeration value="CH_Juliet" />
            <xs:enumeration value="CH_Player" />
            <xs:enumeration value="CH_Victoria" />
            <xs:enumeration value="CH_Zachary" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="check-flag-type">
        <xs:attribute name="flag" type="flag" use="required" />
        <xs:attribute name="eq" type="xs:integer" use="optional" />
        <xs:attribute name="gte" type="xs:integer" use="optional" />
        <xs:attribute name="lte" type="xs:integer" use="optional" />
        <xs:attribute name="inverse" type="xs:boolean" use="optional" />
    </xs:complexType>
    <xs:complexType name="check-item-type">
        <xs:attribute name="item" type="item" use="required" />
        <xs:attribute name="eq" type="xs:integer" use="optional" />
        <xs:attribute name="gte" type="xs:integer" use="optional" />
        <xs:attribute name="lte" type="xs:integer" use="optional" />
        <xs:attribute name="inverse" type="xs:boolean" use="optional" />
    </xs:complexType>
    <xs:complexType name="check-stat-type">
        <xs:attribute name="char" type="character" use="required" />
        <xs:attribute name="stat" type="character-stat" use="required" />
        <xs:attribute name="eq" type="xs:integer" use="optional" />
        <xs:attribute name="gte" type="xs:integer" use="optional" />
        <xs:attribute name="lte" type="xs:integer" use="optional" />
        <xs:attribute name="inverse" type="xs:boolean" use="optional" />
    </xs:complexType>
    <xs:complexType name="check-perk-type">
        <xs:attribute name="perk" type="perk" use="required" />
        <xs:attribute name="inverse" type="xs:boolean" use="optional" />
    </xs:complexType>
    <xs:complexType name="nType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="nop">
                <xs:complexType></xs:complexType>
            </xs:element>
            <xs:element name="prefab">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded" minOccurs="0">
                        <xs:element name="message">
                            <xs:complexType>
                                <xs:attribute name="name" type="xs:string" />
                                <xs:attribute name="string" type="xs:string" />
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="outcome">
                            <xs:complexType>
                                <xs:attribute name="name" type="xs:string" use="required" />
                                <xs:attribute name="output" type="xs:string"  use="required" />
                                <xs:attribute name="destroy" type="xs:integer" />
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                    <xs:attribute name="name" type="prefab" use="optional" />
                    <xs:attribute name="resource" type="xs:string" use="optional" />
                    <xs:attribute name="parent" type="xs:string" use="optional" />
                    <xs:attribute name="target" type="xs:string" use="optional" />
                    <xs:attribute name="destroy" type="xs:string" use="optional" />
                </xs:complexType>
            </xs:element>
            <xs:element name="flag">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="name" type="flag" use="required" />
                            <xs:attribute name="inc" type="xs:string" use="optional" />
                            <xs:attribute name="set" type="xs:string" use="optional" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="text">
                <xs:complexType>
                    <xs:attribute name="name" type="text-data" use="required" />
                    <xs:attribute name="set" type="xs:string" />
                </xs:complexType>
            </xs:element>
            <xs:element name="item">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="name" type="item" use="required" />
                            <xs:attribute name="inc" type="xs:string" />
                            <xs:attribute name="set" type="xs:string" />
                            <xs:attribute name="icon" type="xs:boolean" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="objective">
                <xs:complexType>
                    <xs:attribute name="name" type="objective" use="required" />
                    <xs:attribute name="completed" type="xs:boolean" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="wait">
                <xs:complexType>
                    <xs:attribute name="time" type="xs:decimal" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="anim">
                <xs:complexType>
                    <xs:attribute name="target" type="xs:string" />
                    <xs:attribute name="context" type="xs:string" />
                    <xs:attribute name="trigger" type="xs:string" />
                    <xs:attribute name="int" type="xs:string" />
                    <xs:attribute name="intValue" type="xs:string" />
                    <xs:attribute name="bool" type="xs:string" />
                    <xs:attribute name="boolValue" type="xs:string" />
                </xs:complexType>
            </xs:element>
            <xs:element name="sys" type="xs:string" />
            <xs:element name="dlg">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded" minOccurs="1">
                        <xs:element name="m">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="wait" type="xs:decimal" />
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="char" type="character" />
                    <xs:attribute name="track" type="bone" />
                    <xs:attribute name="jawAnim" type="xs:boolean" />
                    <xs:attribute name="style" type="dialogStyle" />
                </xs:complexType>
            </xs:element>
            <xs:element name="if">
                <xs:complexType>
                    <xs:sequence>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="check-flag" minOccurs="0" type="check-flag-type" />
                            <xs:element name="check-perk" minOccurs="0" type="check-perk-type" />
                            <xs:element name="check-item" minOccurs="0" type="check-item-type" />
                            <xs:element name="check-stat" minOccurs="0" type="check-stat-type" />
                        </xs:choice>
                        <xs:element name="then" minOccurs="1" maxOccurs="1" type="nType" />
                        <xs:element name="else" minOccurs="0" maxOccurs="1" type="nType" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="choice">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="c">
                            <xs:complexType>
                                <xs:choice maxOccurs="unbounded">
                                    <xs:element name="check-flag" type="check-flag-type" minOccurs="0" maxOccurs="unbounded" />
                                    <xs:element name="check-perk" type="check-perk-type" minOccurs="0" maxOccurs="unbounded" />
                                    <xs:element name="check-item" type="check-item-type" minOccurs="0" maxOccurs="unbounded" />
                                    <xs:element name="check-stat" type="check-stat-type" minOccurs="0" maxOccurs="unbounded" />
                                    <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1" />
                                    <xs:element name="lock-reason" type="xs:string" minOccurs="0" maxOccurs="1" />
                                    <xs:element name="then" type="nType" minOccurs="0" maxOccurs="1" />
                                </xs:choice>
                                <xs:attribute name="out" type="xs:string" use="required" />
                                <xs:attribute name="icon" type="choiceIcon" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="help" type="xs:boolean" />
                </xs:complexType>
            </xs:element>
            <xs:element name="stat">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="char" type="character" use="required" />
                            <xs:attribute name="name" type="character-stat" use="required" />
                            <xs:attribute name="set" type="xs:decimal" use="optional" />
                            <xs:attribute name="inc" type="xs:decimal" use="optional" />
                            <xs:attribute name="notify" type="xs:boolean" use="optional" />
                            <xs:attribute name="clamp-a" type="xs:integer" use="optional" />
                            <xs:attribute name="clamp-b" type="xs:integer" use="optional" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="rig-track">
                <xs:complexType>
                    <xs:attribute name="of" type="character" use="required" />
                    <xs:attribute name="target" type="xs:string" />
                    <xs:attribute name="eye" type="xs:decimal"  />
                    <xs:attribute name="head" type="xs:decimal"  />
                    <xs:attribute name="root" type="xs:decimal"  />
                </xs:complexType>
            </xs:element>
            <xs:element name="obj">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string" use="required" />
                    <xs:attribute name="message" type="xs:string" />
                    <xs:attribute name="destroy" type="xs:decimal" />
                    <xs:attribute name="active" type="xs:boolean" />
                </xs:complexType>
            </xs:element>
            <xs:element name="console" type="xs:string" />
            <xs:element name="fade-to-black">
                <xs:complexType>
                    <xs:attribute name="speed" type="xs:string"  use="optional" />
                    <xs:attribute name="time" type="xs:decimal" use="optional" />
                    <xs:attribute name="mode" type="fadeToBlackMode" use="optional" />
                    <xs:attribute name="keep" type="xs:boolean" use="optional" />
                </xs:complexType>
            </xs:element>
            <xs:element name="load">
                <xs:complexType>
                    <xs:attribute name="stage" type="xs:string" use="required" />
                    <xs:attribute name="spawn" type="xs:string" use="optional" />
                </xs:complexType>
            </xs:element>
            <xs:element name="cutscene-outcome">
                <xs:complexType>
                    <xs:attribute name="value" type="cutscene-outcome" use="optional" />
                </xs:complexType>
            </xs:element>
            <xs:element name="node-output">
                <xs:complexType>
                    <xs:attribute name="node" type="xs:string" use="optional" />
                </xs:complexType>
            </xs:element>
        </xs:choice>
        <xs:attribute name="id" type="xs:string" use="optional" />
        <xs:attribute name="out" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:element name="cutscene">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nodes">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="n" type="nType" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== thearchitectx/LIS/Assets/StreamingAssets/Exploration/en/Principal/Drawer2.xml
<?xml version="1.0"?>
<cutscene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../Cutscene.xsd">
    <include node-prefix="inc-quest-brooke-card-">QuestBrookeCardCheck.xml</include>
    <nodes>
        <n id="n">
            <choice>
                <c out="n-check"><text>CHECK DRAWER</text></c>
                <c out="#a"><text>LEAVE</text></c>
            </choice>
        </n>
        <n id="n-check">
            <if>
                <check-flag flag="PRINCIPAL_DRAWER2_UNLOCKED" eq="0" />
                <then>
                    <node-output node="n-check-unlock"/>
                </then>
            </if>

            <anim target="Drawer" bool="open" boolValue="true" />
            <wait time="1" />
            <if>
                <check-flag flag="QUEST_BROOKE_CARD_FOUND_TIP_MEETING" eq="0" />
                <then>
                    <flag name="QUEST_BROOKE_CARD_FOUND_TIP_MEETING" set="1" />
                    <dlg style="subjective">
                        <m>There is a file of school meeting minutes here... Let's check what happened in the latest one...</m>
                    </dlg>
                    
                    <prefab name="PictureViewer">
                        <message name="LoadSprite" string="${Items.ITM_VIP_LIST.IconPath}"/>
                        <message name="SetBorderColor" string="#00000000"/>
                        <message name="HideImageForward" />
                    </prefab>
                    
                    <dlg style="subjective">
                        <m>"Meeting started at 16PM", blah blah blah... "Administration issues", blah, blah...</m>
                        <m wait="1">Wait... this line is interesting...</m>
                    </dlg>
                    <dlg style="remote-subjective">
                        <m wait="0.4">Mr. Wells had to close the meeting earlier due to a urgent call from a student's parent VIP asking to meet him...</m>
                    </dlg>

                    <prefab destroy="PictureViewer" />

                    <dlg style="subjective">
                        <m>So the principal halts anything he's doing to promptly serve the rich students' parents... Interesting...</m>
                    </dlg>

                    <anim target="Drawer" bool="open" boolValue="false" />
                    <node-output node="inc-quest-brooke-card-check"/>
                </then>
                <else>
                    <dlg style="subjective">
                        <m>There is a file of school meeting minutes here... but I already know about the principal's urgent leave to answer a VIP parent...</m>
                    </dlg>
                    <anim target="Drawer" bool="open" boolValue="false" />
                </else>
            </if>
        </n>

        <n id="n-check-unlock">
            <dlg style="subjective">
                <m>Another set of locked drawers... A lockpick could solve the problem...</m>
            </dlg>
            <choice>
                <c out="#a">
                    <check-item item="ITM_LOCKPICK" gte="1" />
                    <text>USE LOCKPICK [x${Items.ITM_LOCKPICK}]</text>
                    <lock-reason>YOU NEED A ${Items.ITM_LOCKPICK.LabelUpper} TO UNLOCK THE DRAWERS</lock-reason>
                    <then>
                        <fade-to-black mode="to" keep="true" />
                        <wait time="1" />
                        <prefab name="LockPick">
                            <message name="MsgGenerate" string="6" />
                            <message name="DisableInput"  />
                        </prefab>
                        <fade-to-black mode="from" />
                        <wait time="1" />
                        <if>
                            <check-flag flag="TUTORIAL_LOCKPICK" eq="0" />
                            <then>
                                <flag name="TUTORIAL_LOCKPICK" set="1" />
                                <sys>
                                    *Move mouse* or use *A,D* keys to position the pick and *left click* when the lock is positioned under a tumbler to activate it\n\n
                                    After discovering the first loose tumbler, you need to figure the correct sequence\n\n
                                    The next correct tumbler is always one directly left or right from the latest you activated\n\n
                                    The lock will reset if you activate a tumbler in the wrong sequence. *Right click* if you want to give up
                                </sys>
                            </then>
                        </if>
                        <prefab name="LockPick">
                            <message name="EnableInput"  />
                            <outcome name="UNLOCKED" output="n-check-unlock-win" />
                            <outcome name="QUIT" output="n-check-unlock-clear" />
                        </prefab>

                    </then>
                </c>
                <c out="_end">
                    <text>LEAVE</text>
                </c>
            </choice>
        </n>


        <n id="n-check-unlock-win">
            <item name="ITM_LOCKPICK" dec="1">THE LOCKPICK NOW USELESS</item>
            <flag name="PRINCIPAL_DRAWER2_UNLOCKED" set="1" />
            <dlg style="subjective">
                <m>Nice... It's unlocked</m>
            </dlg>
            <node-output node="n-check-unlock-clear" />
        </n>

        <n id="n-check-unlock-clear">
            <fade-to-black mode="to" />
            <wait time="0.9" />
            <prefab destroy="LockPick" />
            <node-output node="_end" />
        </n>
    </nodes>
</cutscene>

=== thearchitectx/LIS/Assets/StreamingAssets/Cutscene/en/SchoolHallDroneCard.xml
<?xml version="1.0"?>
<cutscene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../Cutscene.xsd">
    <!-- Runs after checking Brooke's drone memory card -->
    <nodes>
        <n id="n1">
            <wait time="1" />
            <dlg char="CH_Principal" track="Neck">
                <m>It was him... I know... He's the who did this little prank...</m>
                <m wait="1">Be prepared, kid... One day I'll catch you in the act... Your expulsion memo is ready, just waiting for this day...</m>
            </dlg>

            <anim int="step" intValue="2" />
            <wait time="1" />

            <dlg char="CH_Principal" track="Neck">
                <m>Damn it... And now I have to deal with Justin again...</m>
                <m>Urgh... I hate my life...</m>
            </dlg>

            <fade-to-black mode="to" keep="true" />
            <wait time="0.5" />
            <sfx clip="door-transition" wait="true" />
            <wait time="0.5" />

            <objective name="OBJ_PrincipalPrank" completed="true" />
            <objective name="OBJ_BrookeMemoryCard01" completed="true" />
            <objective name="OBJ_BrookeMemoryCard02" completed="false" />

            <load stage="school-hall-01" spawn="Player Spawn/Corner A" />
        </n>
    </nodes>
</cutscene>

=== thearchitectx/LIS/Assets/StreamingAssets/Exploration/en/Hallway/TrashCan.xml
<?xml version="1.0"?>
<cutscene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../Cutscene.xsd">
    <nodes>
        <n id="root">
            <switch-text check="${Texts.TXT_ARG_0}" text="TXT_TMP_0">
                <case eq="1">A trashcan... Apparently an invisible object for most students in this school...</case>
                <case eq="2">Yet another trashcan...</case>
                <case eq="3">A trashcan... Brings back bad memories...</case>
                <case eq="4">Another trashcan... There are plenty of those around here...</case>
            </switch-text>
            <dlg style="subjective">
                <m>${Texts.TXT_TMP_0}</m>
            </dlg>
            
            <choice>
                <c out="n2-rummage">
                    <check-flag flag="QUEST_KATE_LOCKER" eq="1" />
                    <text>Rummage</text>
                </c>
                <c out="trash-dump">
                    <check-item item="ITM_TRASH" gte="1" />
                    <text>Discard Trash</text>
                </c>
                <c out="trash-get">
                    <check-item item="ITM_TRASH" lte="3" />
                    <text>Collect Trash</text>
                </c>
                <c out="#a"><text>Leave</text></c>
            </choice>
        </n>

        <n id="n2-rummage">
            <fade-to-black mode="to-from" keep="false" />
            <wait time="2" />
            <if>
                <check-flag flag="QUEST_KATE_LOCKER_KEY_LOCATION" eq-str="${Texts.TXT_ARG_0}" />
                <then>
                    <dlg style="subjective">
                        <m>There's a small key in the trash can...</m>
                        <m>It's probably the one used to mess with a locker combination...</m>
                    </dlg>
        
                    <flag name="QUEST_KATE_LOCKER" set="2" />
                    <item name="ITM_LOCKER_KEY" set="1">*LOCKER KEY* FOUND</item>
                    <objective name="OBJ_KateHelpLockerFindKey" completed="true" />
                    <objective name="OBJ_KateHelpLockerOpenLocker" completed="false" />
                </then>
                <else>
                    <dlg style="subjective">
                        <m>Nothing useful here...</m>
                    </dlg>
                </else>
            </if>
        </n>
        
        <n id="trash-dump">
            <fade-to-black keep="false" />
            <wait time="1" />
            <item name="ITM_TRASH" set="0">DISCARDED ALL TRASH</item>
            <dlg style="subjective">
                <m>Trash is now in the place it belongs...</m>
            </dlg>
        </n>

        <n id="trash-get">
            <fade-to-black keep="false" />
            <wait time="1" />

            <item name="ITM_TRASH" inc="1">Collected trash! Yay!</item>

            <dlg style="subjective">
                <m>Just honing my homeless skills, I guess...</m>
            </dlg>
        </n>
    </nodes>
</cutscene>
