=== thearchitectx/LIS/Assets/StreamingAssets/Cutscene.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="dialogStyle">
        <xs:restriction base="xs:string">
            <xs:enumeration value="whisper"/>
            <xs:enumeration value="remote"/>
            <xs:enumeration value="remote-subjective"/>
            <xs:enumeration value="default"/>
            <xs:enumeration value="subjective"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="fadeToBlackMode">
        <xs:restriction base="xs:string">
            <xs:enumeration value="to"/>
            <xs:enumeration value="from" />
            <xs:enumeration value="to-from" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="prefab">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PictureViewer"/>
            <xs:enumeration value="PictureTaker" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cutscene-outcome">
        <xs:restriction base="xs:string">
            <xs:enumeration value="_destroyObject"/>
            <xs:enumeration value="_destroyParent"/>
            <xs:enumeration value="_end"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="bone">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Hips" />
            <xs:enumeration value="Spine" />
            <xs:enumeration value="Spine1" />
            <xs:enumeration value="Spine2" />
            <xs:enumeration value="Neck" />
            <xs:enumeration value="Head" />
            <xs:enumeration value="LeftEye" />
            <xs:enumeration value="RightEye" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="text-data">
        <xs:restriction base="xs:string">
            <xs:enumeration value="KATE_HALLWAY_PICTURE" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="perk">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PRK_SMELLY" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="choiceIcon">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DICK_INTELLIGENCE" />
            <xs:enumeration value="DICK_CHARISMA" />
            <xs:enumeration value="DICK_KARMA_GOOD" />
            <xs:enumeration value="DICK_KARMA_EVIL" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="flag">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DICK_DARING" />
            <xs:enumeration value="DICK_INTELLIGENCE" />
            <xs:enumeration value="DICK_CHARISMA" />
            <xs:enumeration value="DICK_KARMA" />
            <xs:enumeration value="CLASSROOM_TRASH_CAN_TRASH_COUNT" />
            <xs:enumeration value="BROOKE_MET" />
            <xs:enumeration value="BROOKE_ABOUT_MAX_AND WARREN" /> <!-- (1)Propose revenge (2)Tried to help -->
            <xs:enumeration value="HALLWAY_TRASH_CAN_A_TRASH_COUNT" />
            <xs:enumeration value="HALLWAY_TRASH_CAN_B_TRASH_COUNT" />
            <xs:enumeration value="HALLWAY_TRASH_CAN_C_TRASH_COUNT" />
            <xs:enumeration value="HALLWAY_TRASH_CAN_D_TRASH_COUNT" />
            <xs:enumeration value="HALLWAY_TRIED_ENTER_ROOM103" />
            <xs:enumeration value="INTRO_TRASH_SCORE" />
            <xs:enumeration value="INTRO_TALK_VICTORIA" />
            <xs:enumeration value="INTRO_CHECK_VICTORIA" />
            <xs:enumeration value="JULIE_ZACHARY_MAKE_OUT_SEEN" />
            <xs:enumeration value="KATE_FIRST_MET" />
            <xs:enumeration value="PICKED_BROOKE_NOTE" />
            <xs:enumeration value="QUEST_BROOKE_CARD" /> <!-- (1)Started  -->
            <xs:enumeration value="QUEST_KATE_LOCKER" /> <!-- (1)Started (2)Searching Key (3)Delivered Key</xs:documentation></xs:annotation></xs:enumeration -->
            <xs:enumeration value="QUEST_JEFFERSON_TAKE_PIC" /><!-- (1)Took Lame Pic (2)Took cool pic (11)Delivered Lame pic (12)Delivered Cool Pic -->
            <xs:enumeration value="TMP_1" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="character-stat">
        <xs:restriction base="xs:string">
            <xs:enumeration value="AFFINITY" />
            <xs:enumeration value="INTEL" />
            <xs:enumeration value="INTEL_0" />
            <xs:enumeration value="INTEL_1" />
            <xs:enumeration value="INTEL_2" />
            <xs:enumeration value="INTEL_3" />
            <xs:enumeration value="INTEL_4" />
            <xs:enumeration value="INTEL_5" />
            <xs:enumeration value="INTEL_6" />
            <xs:enumeration value="INTEL_7" />
            <xs:enumeration value="INTEL_8" />
            <xs:enumeration value="INTEL_9" />
            <xs:enumeration value="CORRUPTION" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="objective">
        <xs:restriction base="xs:string">
            <xs:enumeration value="OBJ_BrookeMemoryCard" />
            <xs:enumeration value="OBJ_IntroCollectTrash" />
            <xs:enumeration value="OBJ_IntroTalk" />
            <xs:enumeration value="OBJ_JeffersonFirstPicTake" />
            <xs:enumeration value="OBJ_KateHelpLockerOpenLocker" />
            <xs:enumeration value="OBJ_KateHelpLockerFindKey" />
            <xs:enumeration value="OBJ_JeffersonFirstPicBring" />
            <xs:enumeration value="OBJ_TalkToThePrincipal" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="item">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ITM_LOCKER_KEY" />
            <xs:enumeration value="ITM_MONEY" />
            <xs:enumeration value="ITM_TRASH" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="character">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CH_Brooke" />
            <xs:enumeration value="CH_Kate" />
            <xs:enumeration value="CH_Jefferson" />
            <xs:enumeration value="CH_Juliet" />
            <xs:enumeration value="CH_Player" />
            <xs:enumeration value="CH_Victoria" />
            <xs:enumeration value="CH_Zachary" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="check-flag-type">
        <xs:attribute name="flag" type="flag" use="required" />
        <xs:attribute name="eq" type="xs:integer" use="optional" />
        <xs:attribute name="gte" type="xs:integer" use="optional" />
        <xs:attribute name="lte" type="xs:integer" use="optional" />
        <xs:attribute name="inverse" type="xs:boolean" use="optional" />
    </xs:complexType>
    <xs:complexType name="check-item-type">
        <xs:attribute name="item" type="item" use="required" />
        <xs:attribute name="eq" type="xs:integer" use="optional" />
        <xs:attribute name="gte" type="xs:integer" use="optional" />
        <xs:attribute name="lte" type="xs:integer" use="optional" />
        <xs:attribute name="inverse" type="xs:boolean" use="optional" />
    </xs:complexType>
    <xs:complexType name="check-stat-type">
        <xs:attribute name="char" type="character" use="required" />
        <xs:attribute name="stat" type="character-stat" use="required" />
        <xs:attribute name="eq" type="xs:integer" use="optional" />
        <xs:attribute name="gte" type="xs:integer" use="optional" />
        <xs:attribute name="lte" type="xs:integer" use="optional" />
        <xs:attribute name="inverse" type="xs:boolean" use="optional" />
    </xs:complexType>
    <xs:complexType name="check-perk-type">
        <xs:attribute name="perk" type="perk" use="required" />
        <xs:attribute name="inverse" type="xs:boolean" use="optional" />
    </xs:complexType>
    <xs:complexType name="nType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="nop">
                <xs:complexType></xs:complexType>
            </xs:element>
            <xs:element name="prefab">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded" minOccurs="0">
                        <xs:element name="message">
                            <xs:complexType>
                                <xs:attribute name="name" type="xs:string" />
                                <xs:attribute name="string" type="xs:string" />
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="outcome">
                            <xs:complexType>
                                <xs:attribute name="name" type="xs:string" use="required" />
                                <xs:attribute name="output" type="xs:string"  use="required" />
                                <xs:attribute name="destroy" type="xs:integer" />
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                    <xs:attribute name="name" type="prefab" use="optional" />
                    <xs:attribute name="resource" type="xs:string" use="optional" />
                    <xs:attribute name="parent" type="xs:string" use="optional" />
                    <xs:attribute name="target" type="xs:string" use="optional" />
                    <xs:attribute name="destroy" type="xs:string" use="optional" />
                </xs:complexType>
            </xs:element>
            <xs:element name="flag">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="name" type="flag" use="required" />
                            <xs:attribute name="inc" type="xs:string" use="optional" />
                            <xs:attribute name="set" type="xs:string" use="optional" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="text">
                <xs:complexType>
                    <xs:attribute name="name" type="text-data" use="required" />
                    <xs:attribute name="set" type="xs:string" />
                </xs:complexType>
            </xs:element>
            <xs:element name="item">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="name" type="item" use="required" />
                            <xs:attribute name="inc" type="xs:string" />
                            <xs:attribute name="set" type="xs:string" />
                            <xs:attribute name="icon" type="xs:boolean" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="objective">
                <xs:complexType>
                    <xs:attribute name="name" type="objective" use="required" />
                    <xs:attribute name="completed" type="xs:boolean" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="wait">
                <xs:complexType>
                    <xs:attribute name="time" type="xs:decimal" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="anim">
                <xs:complexType>
                    <xs:attribute name="target" type="xs:string" />
                    <xs:attribute name="context" type="xs:string" />
                    <xs:attribute name="trigger" type="xs:string" />
                    <xs:attribute name="int" type="xs:string" />
                    <xs:attribute name="intValue" type="xs:string" />
                    <xs:attribute name="bool" type="xs:string" />
                    <xs:attribute name="boolValue" type="xs:string" />
                </xs:complexType>
            </xs:element>
            <xs:element name="sys" type="xs:string" />
            <xs:element name="dlg">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded" minOccurs="1">
                        <xs:element name="m">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="wait" type="xs:decimal" />
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="char" type="character" />
                    <xs:attribute name="track" type="bone" />
                    <xs:attribute name="jawAnim" type="xs:boolean" />
                    <xs:attribute name="style" type="dialogStyle" />
                </xs:complexType>
            </xs:element>
            <xs:element name="if">
                <xs:complexType>
                    <xs:sequence>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="check-flag" minOccurs="0" type="check-flag-type" />
                            <xs:element name="check-perk" minOccurs="0" type="check-perk-type" />
                            <xs:element name="check-item" minOccurs="0" type="check-item-type" />
                            <xs:element name="check-stat" minOccurs="0" type="check-stat-type" />
                        </xs:choice>
                        <xs:element name="then" minOccurs="1" maxOccurs="1" type="nType" />
                        <xs:element name="else" minOccurs="0" maxOccurs="1" type="nType" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="choice">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="c">
                            <xs:complexType>
                                <xs:choice maxOccurs="unbounded">
                                    <xs:element name="check-flag" type="check-flag-type" minOccurs="0" maxOccurs="unbounded" />
                                    <xs:element name="check-perk" type="check-perk-type" minOccurs="0" maxOccurs="unbounded" />
                                    <xs:element name="check-item" type="check-item-type" minOccurs="0" maxOccurs="unbounded" />
                                    <xs:element name="check-stat" type="check-stat-type" minOccurs="0" maxOccurs="unbounded" />
                                    <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1" />
                                    <xs:element name="lock-reason" type="xs:string" minOccurs="0" maxOccurs="1" />
                                    <xs:element name="then" type="nType" minOccurs="0" maxOccurs="1" />
                                </xs:choice>
                                <xs:attribute name="out" type="xs:string" use="required" />
                                <xs:attribute name="icon" type="choiceIcon" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="help" type="xs:boolean" />
                </xs:complexType>
            </xs:element>
            <xs:element name="stat">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="char" type="character" use="required" />
                            <xs:attribute name="name" type="character-stat" use="required" />
                            <xs:attribute name="set" type="xs:decimal" use="optional" />
                            <xs:attribute name="inc" type="xs:decimal" use="optional" />
                            <xs:attribute name="notify" type="xs:boolean" use="optional" />
                            <xs:attribute name="clamp-a" type="xs:integer" use="optional" />
                            <xs:attribute name="clamp-b" type="xs:integer" use="optional" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="rig-track">
                <xs:complexType>
                    <xs:attribute name="of" type="character" use="required" />
                    <xs:attribute name="target" type="xs:string" />
                    <xs:attribute name="eye" type="xs:decimal"  />
                    <xs:attribute name="head" type="xs:decimal"  />
                    <xs:attribute name="root" type="xs:decimal"  />
                </xs:complexType>
            </xs:element>
            <xs:element name="obj">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string" use="required" />
                    <xs:attribute name="message" type="xs:string" />
                    <xs:attribute name="destroy" type="xs:decimal" />
                    <xs:attribute name="active" type="xs:boolean" />
                </xs:complexType>
            </xs:element>
            <xs:element name="console" type="xs:string" />
            <xs:element name="fade-to-black">
                <xs:complexType>
                    <xs:attribute name="speed" type="xs:string"  use="optional" />
                    <xs:attribute name="time" type="xs:decimal" use="optional" />
                    <xs:attribute name="mode" type="fadeToBlackMode" use="optional" />
                    <xs:attribute name="keep" type="xs:boolean" use="optional" />
                </xs:complexType>
            </xs:element>
            <xs:element name="load">
                <xs:complexType>
                    <xs:attribute name="stage" type="xs:string" use="required" />
                    <xs:attribute name="spawn" type="xs:string" use="optional" />
                </xs:complexType>
            </xs:element>
            <xs:element name="cutscene-outcome">
                <xs:complexType>
                    <xs:attribute name="value" type="cutscene-outcome" use="optional" />
                </xs:complexType>
            </xs:element>
            <xs:element name="node-output">
                <xs:complexType>
                    <xs:attribute name="node" type="xs:string" use="optional" />
                </xs:complexType>
            </xs:element>
        </xs:choice>
        <xs:attribute name="id" type="xs:string" use="optional" />
        <xs:attribute name="out" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:element name="cutscene">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nodes">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="n" type="nType" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== thearchitectx/LIS/Assets/StreamingAssets/Cutscene/en/BrookeSelfie.xml
<?xml version="1.0"?>
<cutscene
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../Cutscene.xsd">
    <nodes>
        <n id="n1">
            <flag name="QUEST_BROOKE_CARD" inc="10"></flag>
            <wait time="5" />
            <prefab name="TimelineUI">
                <message name="DisableUI"/>
            </prefab>

            <dlg style="subjective">
                <m>So... That "hacking evidence" she was talking about is all bullshit...</m>
                <m>This clip is what she didn't wanted the principal to discover...</m>
            </dlg>
            
            <wait time="1" />
            
            <dlg style="subjective">
                <m>Well... I'm pretty sure using the school restrooms to record this kind of content is against some rule...</m>
            </dlg>

            <sys>
                You can use your phone video player controls to pause, and change playback speed\n\n
                You can drag the progress bar to pause the clip in a specific time\n\n
                Keep the mouse quiet to hide the UI\n\n
                Press the 'X' button to exit
            </sys>

            <prefab name="TimelineUI">
                <message name="EnableUI"/>
                <outcome name="CLOSE" output="#a" />
            </prefab>
            
            <fade-to-black keep="true" speed="1" />
            <wait time="1" />
            
            <load stage="principal-office-drone-card" />
        </n>
    </nodes>
</cutscene>

=== thearchitectx/LIS/Assets/StreamingAssets/Exploration/en/SchoolHall/Startup.xml
<?xml version="1.0"?>
<cutscene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../Cutscene.xsd">
    <nodes>
        <n id="n1">
            <if>
                <check-flag flag="QUEST_JEFFERSON_TAKE_PIC" gte="10" />
                <then>
                    <prefab resource="Exploration/SchoolHall/Dynamics/CH_Brooke" target="CH_Brooke" parent="Dynamic" />
                </then>
            </if>
            <cutscene-outcome value="_destroyObject" />
        </n>
    </nodes>
</cutscene>

=== thearchitectx/LIS/Assets/StreamingAssets/Exploration/en/Principal/QuestBrookeCardCheck.xml
<?xml version="1.0"?>
<cutscene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../Cutscene.xsd">
    <nodes>
        <n id="check">
            <flag name="TMP_1" set="0" />
            <if>
                <check-flag flag="QUEST_BROOKE_CARD_FOUND_TIP_MEETING" gte="1"/>
                <then>
                    <flag name="TMP_1" inc="1" />
                </then>
            </if>
            <if>
                <check-flag flag="QUEST_BROOKE_CARD_FOUND_TIP_FINANCE" gte="1"/>
                <then>
                    <flag name="TMP_1" inc="1" />
                </then>
            </if>
            <if>
                <check-item item="ITM_VIP_LIST" gte="1" />
                <then>
                    <flag name="TMP_1" inc="1" />
                </then>
            </if>
            <if>
                <check-flag flag="TMP_1" gte="3"/>
                <then>
                    <dlg style="subjective">
                        <m>Hum... If the Principal received a message from Sean Prescott's asking him to go urgently to some distant place, he'd leave the office free for exploration for a few minutes!</m>
                        <m>A spoofed message using Prescott's number would do the trick...</m>
                        <m>The best place to do this would be right at his door...</m>
                    </dlg>
                    <objective name="OBJ_PrincipalPrank" completed="false" />
                </then>
                <else>
                    <dlg style="subjective">
                        <m>This piece of info could help me figure a way to make the Principal leave his office for some time...</m>
                        <m>But it seems there are more pieces of this puzzle to be found...</m>
                    </dlg>
                    <console>FOUND *${Flags.TMP_1}* OF *3* UNIQUE '*PRINCIPAL PRANK*' TIPS</console>
                </else>
            </if>
        </n>
    </nodes>
</cutscene>

=== thearchitectx/LIS/Assets/StreamingAssets/Exploration/en/Principal/Startup.xml
<?xml version="1.0"?>
<cutscene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../Cutscene.xsd">
    <include node-prefix="exploration-">../_Lib/Exploration.xml</include>
    <nodes>
        <n id="n1">
            <inject node="exploration-root" />
            <!-- JUSTIN -->
            <prefab resource="Exploration/Principal/JustinWall/CH_Justin" target="CH_Justin" parent="Dynamic" />
            <!-- JUSTIN FIRST MET -->
            <if>
                <check-flag flag="JUSTIN_MET" eq="0" />
                <then>
                    <dlg char="CH_Justin" char-transform="../Dynamic/CH_Justin" track="Neck" timed="5">
                        <m>Psst! Hey... Over here...</m>
                    </dlg>
                </then>
            </if>
            <!-- SPAWN LOST MONEY #2 -->
            <if>
                <check-flag flag="LOST_MONEY_FOUND" bit-unset="2" />
                <then>
                    <prefab resource="Exploration/Principal/Dynamic/DollarBill" target="DollarBill" parent="Dynamic" />
                </then>
            </if>
            <!-- COMMENT PRINCIPAL WAR -->
            <if>
                <check-flag flag="PRINCIPAL_CH_MET" eq="1" />
                <then>
                    <flag name="PRINCIPAL_CH_MET" set="2" />
                    <flag name="#DISABLE_PLAYER" set="1" />
                    
                    <dlg style="subjective">
                        <m>So... He declares open war...</m>
                        <m wait="1">Well... I have no other option than fighting with the weapons I have...</m>
                    </dlg>

                    <flag name="#DISABLE_PLAYER" set="0" />
                </then>
            </if>

            <cutscene-outcome value="_destroyObject" />
        </n>
    </nodes>
</cutscene>

=== thearchitectx/LIS/Assets/StreamingAssets/Exploration/en/_Lib/SmoothTalkTutorial.xml
<?xml version="1.0"?>
<cutscene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../Cutscene.xsd">
    <nodes>
        <n id="lib-play">
            <flag name="DATA_SMOOTH_TALK_PLAYS" inc="1" />
            <if>
                <check-flag flag="DATA_SMOOTH_TALK_PLAYS" eq="1" />
                <then>
                    <sys>
                        SMOOTH TALK TUTORIAL(1/2)\n\n
                        Did you know girls also have a D.I.C.K.?\n\nIt's not a trap!\n\n
                        It means they'll use Daring, Charisma and Intelligence moves to beat your Smooth Talk attempt!\n\n
                        To win the turn, you must *match the D.I.C.K move* she used with your own...\n\n
                        Deplete her stamina to have a successful Smooth Talk session!
                    </sys>
                    <sys>
                        SMOOTH TALK TUTORIAL(2/2)\n\n
                        *Karma* moves may be available sometimes during your turn!\n\n
                        The *GOOD* Karma move allows you to recover some stamina...\n\n
                        The *EVIL* Karma move performs a powerful blow against your opponent...\n\n
                        Notice Karma moves will only have effect if it matches your current character Karma balance...\n\n
                        Neutral characters suck and won't earn any effect!\n
                    </sys>
                </then>
            </if>
        </n>

        <n id="lib-win">
            <flag name="DATA_SMOOTH_TALK_WINS" inc="1" />
            <if>
                <check-flag flag="DATA_SMOOTH_TALK_WINS" eq="1" />
                <then>
                    <sys>
                        SMOOTH TALK TUTORIAL\n\n
                        When you win a Smooth Talk session, a choice will follow...\n\n
                        The opponent will be stunned, but it doesn't mean anything you ask will be accepted!\n\n
                        Choose wisely ! (or try your luck)
                    </sys>
                </then>
            </if>
        </n>
    </nodes>
</cutscene>

=== thearchitectx/LIS/Assets/StreamingAssets/Exploration/en/Classroom/DoorOut.xml
<?xml version="1.0"?>
<cutscene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../Cutscene.xsd">
    <nodes>
        <n id="n1">
            <choice>
                <c out="n2"><text>Go to Hallway</text></c>
                <c out="#a"><text>Back</text></c>
            </choice>
        </n>
        <n id="n2">
            <fade-to-black keep="true" />
            <wait time="1" />
            <load stage="hallway-01" spawn="Player Spawn/Art Class" />
        </n>
    </nodes>
</cutscene>
